trigger:
  - master

jobs:
  - job: 'Test'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        py27:
          python.version: '2.7'
          tox.env: py27
        py37:
          python.version: '3.7'
          tox.env: py37
        docs:
          python.version: '3.7'
          tox.env: docs
    steps:
      - task: PythonScript@0
        displayName: Print a message
        inputs:
          scriptSource: filePath
          scriptPath: 'build/print.py'
          arguments: 'a b'
          #pythonInterpreter: # Optional
          #workingDirectory: # Optional
          #failOnStderr: false # Optional