trigger:
  - master

jobs:
  - job: 'Restructure'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: PythonScript@0
        displayName: Print a message
        inputs:
          scriptSource: filePath
          scriptPath: 'build/print.py'
          arguments: 'bfk1.json kunnskap.json'
#          arguments: 'bfk1.json kodeliste.json kunnskap.json'
          #pythonInterpreter: # Optional
          #workingDirectory: # Optional
          #failOnStderr: false # Optional